### ISSUE TITLE
bbctl not checking if artifact exists for correct architecture

### ISSUE THREAD

**Issue by valadect** [beeper/bridge-manager#13]
The latest commit of mautrix discord `2138b611` doesn't have a build artifact for darwin amd64. 

However bbctl still recognises the new commit and tries to download the binary for a missing building artifact and instead downloads the html source of the mau.dev login page. 

Thus when trying to run `bbctl run sh-discord` you get a `exec format error` as it's not a binary.

Downloading older build artifacts for the correct arch doesn't work either as bbctl still tries to update them.

**Comment by emitchgustafson** [comment]
@valadect, I just found this ticket and I was able to work around this same issue on mac amd64 signalgo bridge using the -n flag. So `bbctl run -n sh-discord` should tell it not to bother checking for an update.

**Comment by tulir** [comment]
Intel macOS binaries are deprecated, but `bbctl run` now has a `--compile` flag to have it automatically clone the bridge repo and build it locally.
