### ISSUE TITLE
Maybe add support for Snapchat in the future ?

### ISSUE THREAD

**Issue by HGStyle** [beeper/bridge-manager#15]
Hello, I would really like to have support for Snapchat (messages only !). I know adding support to a message system is pretty hard to make and maintain, but there is absolutely no problem if it's not now !
Thanks, and GG for this huge project !

**Comment by cameronaaron** [comment]
there is no snapchat bridge

**Comment by tulir** [comment]
This is not the place to request new bridges

**Comment by HGStyle** [comment]
> there is no snapchat bridge

That's the point, actually.

> This is not the place to request new bridges

Ah. Could you tell me where to ask, please ?
