### ISSUE TITLE
Any plans for including bridges to the fediverse (Mastodon, Friendica)?

### ISSUE THREAD

**Issue by jerry1970** [beeper/bridge-manager#18]
Having Beeper saves me several pinned tabs in a separate browser window for all my chat apps (each tab asking for a load of memory as well), but I still have a Friendica and a Mastodon account in tabs. Is a birdge to the fediverse in the plans?

Thanks!

**Comment by tulir** [comment]
This is not the place to request new bridges. Bridging those to a chat app also doesn't make much sense.
