### ISSUE TITLE
Add an official e-mail bridge.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [beeper/bridge-manager#20]
https://github.com/beeper/bridge-manager/tree/063928568d5d9c0c2c7ae072570f3878a159dddd?tab=readme-ov-file#official-bridge-list doesn't list one despite e-mail being the most used federated communication platform in the world, and Matrix officially recognizing https://matrix.org/ecosystem/bridges/email/.

**Comment by tulir** [comment]
The official bridge list is for bridges that bbctl can install and run directly without requiring the user to install the bridge manually. Only bridges that are meant for personal use and reach a certain standard of quality will be officially supported in bbctl. I don't think there are any such email bridges currently, and we currently don't have any plans to write one.

Postmoogle seems to be actively maintained and is probably of decent quality, but it doesn't seem to be meant for personal use.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/beeper/bridge-manager/issues/20#issuecomment-1962436804

Thanks for the sensible rationale, @tulir.
