### ISSUE TITLE
Slack bridge doesn't work on ARM64 Mac

### ISSUE THREAD

**Issue by heywoodlh** [beeper/bridge-manager#35]
Getting the following when I try to run the Slack bridge on an M1 Mac:

```
heywoodlh@mac-mini ~ % bbctl run sh-slack-000
Finding latest version of mautrix-slack from mau.dev
failed to update bridge: failed to find URL for job "build macos arm64" on branch main of mautrix/slack
```

Rosetta is enabled on this Mac, I'd be fine with using x86_64 Darwin if Mautrix Slack bridge if there is one. Not sure how to proceed and it's a pretty low priority for me so I'm not super concerned with fixing this -- but wanted to report it.

**Comment by stateless** [comment]
Same problem in amd64.  

Comment in #self-hosting:beeper.com was an update to bbctl was required.
