### ISSUE TITLE
nachrichten werden nicht ordnungsgemäß angezeigt

### ISSUE THREAD

**Issue by SnakeEater96** [beeper/bridge-manager#37]
Hallo,

habe mir eben den whatsapp bridge bot eingespielt da ich 2 instanzen benötige und habe das bei matrix-synapse eingebunden

aber die nachrichten werden nicht so angezeigt wie in der beeper app (beispiel meine nachrichten werden nicht angezeigt)

habe die config genutzt 

https://github.com/beeper/bridge-manager/blob/main/bridgeconfig/whatsapp.tpl.yaml

**Comment by tulir** [comment]
Support is only available in English. GitHub issues should primarily be used for bugs and feature requests, for help with using bbctl asking in the Matrix room is more appropriate ([#self-hosting:beeper.com](https://matrix.to/#/#self-hosting:beeper.com)).

Also, Synapse is not involved at all when using bridge-manager/bbctl. If you're using Synapse, you're not using bbctl.
