### ISSUE TITLE
Repeated 502 errors with non-JSON body when running bluebubbles bridge

### ISSUE THREAD

**Issue by ChaseThomas** [beeper/bridge-manager#43]
When attempting to run the bluebubbles bridge, I'm encountering repeated 502 errors with non-JSON body responses.

`/usr/local/bin/bbctl run --local-dev --param 'bluebubbles_url=http://localhost:1234/' --param 'bluebubbles_password=<passwordfiller>' --param 'imessage_platform=bluebubbles' sh-imessage`

spits out the attached screenshot of errors.

<img width="973" alt="Screenshot 2024-09-09 at 11 10 02 PM" src="https://github.com/user-attachments/assets/e18e1099-adb4-4245-8dab-437d33ee9ee9">

bbctl-macos-amd64 version v0.12.2 
MacOS 12.7.4

**Comment by tulir** [comment]
When using `--local-dev`, you're responsible for updating the config yourself. It's recommended to not use that flag.
