### ISSUE TITLE
SSL Certificate expired: 📟 Beeper Tools Intermediate CA

### ISSUE THREAD

**Issue by tjpalanca** [beeper/bridge-manager#44]
I'm self-hosting an iMessage bridge using:

`bbctl run --param 'imessage_platform=mac' sh-imessage`

The SSL certificate of the server has expired recently, causing the following error:

```
failed to register appservice: request error: Put "https://<BEEPER IP>/megahungry-stable-ex130-8/<USER>/_matrix/asmux/mxauth/appservice/<USER>/sh-imessage": tls: failed to verify certificate: x509: “📟 Beeper Tools Intermediate CA” certificate is not trusted
```

Is this expected?

**Comment by tulir** [comment]
That is expected when using an outdated bbctl version
