### ISSUE TITLE
Error while running bridge manager with docker

### ISSUE THREAD

**Issue by ma-04** [beeper/bridge-manager#49]
Running bridge-manager with docker causes error, command ran 
```
docker run \                                                                                            
        -v $(pwd):/data \
        -e MATRIX_ACCESS_TOKEN=dfkdfkdkjfdjksf90dsfdf \
        ghcr.io/beeper/bridge-manager 'sh-telegram'
```
to which the output is
```/usr/local/bin/run-bridge.sh: line 4: $1: unbound variable```

My environment:
Ubuntu Desktop 24.04
Ubuntu Server 24.04
Docker installed from docker official repository

I already have a solution, #47 and it works.

**Comment by Chrismarsh** [comment]
I am wondering if and when #47 might be merged in? I am running into the same problem.

**Comment by ma-04** [comment]
waiting for @tulir to merge it.

**Comment by devnoname120** [comment]
You can override the entrypoint by using the `--entrypoint` argument in the `docker run` command.

**Comment by Chrismarsh** [comment]
I've been trying that -- I'm using portainer to manager my docker images, and I cannot get the syntax in the PR to work.

**Comment by ma-04** [comment]
Just use this in Portainer Entrypoint option
```bash
/usr/local/bin/run-bridge.sh sh-whatsapp
```

**Comment by ma-04** [comment]
#47 has been merged.
